# Generated by Django 4.1 on 2022-08-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_blog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
