# Generated by Django 4.1 on 2022-08-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='about',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='about',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='about',
            name='location',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='about',
            name='profile',
        ),
    ]
