# Generated by Django 4.1 on 2022-08-27 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_about_email_remove_about_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='followlink',
            field=models.TextField(default=datetime.datetime(2022, 8, 27, 10, 5, 25, 911877, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
